---
title: "Lauren"
author: "Lauren"
date: "11/14/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# Load the data
library(tidyverse)

diversity_school <- 
  read_csv("https://raw.githubusercontent.com/Reed-Statistics/data-viz-competition-2020/main/data/diversity_school.csv") %>%
  dplyr::select(-X1)

historical_tuition <- 
  read_csv("https://raw.githubusercontent.com/Reed-Statistics/data-viz-competition-2020/main/data/historical_tuition.csv") %>%
  dplyr::select(-X1)

salary_potential <-
  read_csv("https://raw.githubusercontent.com/Reed-Statistics/data-viz-competition-2020/main/data/salary_potential.csv") %>%
  dplyr::select(-X1)

tuition_cost <-
  read_csv("https://raw.githubusercontent.com/Reed-Statistics/data-viz-competition-2020/main/data/tuition_cost.csv") %>% 
  dplyr::select(-X1)

tuition_income <-
  read_csv("https://raw.githubusercontent.com/Reed-Statistics/data-viz-competition-2020/main/data/tuition_income.csv") %>%
  dplyr::select(-X1)
```

```{r}
school_cats <- read.csv("oleks_data.csv")
```

```{r}
school_cats %>%
  filter(CONTROL == 1 | CONTROL == 2) %>%
  ggplot(aes(x = stem_percent, y = make_world_better_percent)) +
  geom_point(aes(color = early_career_pay, shape = factor(CONTROL)), alpha = 0.5)
```

```{r}
school_cats %>%
  count(CONTROL)
```

```{r}
school_cats %>%
  filter(CONTROL == 1 | CONTROL == 2) %>%
  ggplot(aes(x=factor(CONTROL), y= make_world_better_percent)) +
  geom_boxplot()
```

```{r}
school_cats %>%
  filter(CONTROL == 1 | CONTROL == 2) %>%
  ggplot(aes(x=stem_percent, y=mid_career_pay)) +
  geom_point(aes(color = factor(CONTROL)))
```

```{r}
library(GGally)

# Plot
ggparcoord(salary_potential,
    columns = c(4,5),
    scale = "globalminmax",
    alphaLines = 0.3
    ) 

#color by slope 
```

```{r}
school_cats %>%
  ggplot(aes(x= state_name, y=stem_percent)) +
  geom_boxplot()
```

